package com.hedgehog.domain;
// Generated 2012-9-2 17:37:25 by Hibernate Tools 3.2.2.GA



/**
 * SysField generated by hbm2java
 */
public class SysField  implements java.io.Serializable {


     private String fieldId;
     private String fkey;
     private String fcname;
     private String fremark;

   
   
    public String getFieldId() {
        return this.fieldId;
    }
    
    public void setFieldId(String fieldId) {
        this.fieldId = fieldId;
    }
    public String getFkey() {
        return this.fkey;
    }
    
    public void setFkey(String fkey) {
        this.fkey = fkey;
    }
    public String getFcname() {
        return this.fcname;
    }
    
    public void setFcname(String fcname) {
        this.fcname = fcname;
    }
    public String getFremark() {
        return this.fremark;
    }
    
    public void setFremark(String fremark) {
        this.fremark = fremark;
    }




}


