package com.hedgehog.domain;
// Generated 2012-9-2 17:37:25 by Hibernate Tools 3.2.2.GA



/**
 * SysRole generated by hbm2java
 */
public class SysRole  implements java.io.Serializable {


     private String roleId;
     private String ruserId;
     private String rroleName;
     private String rdescription;
     private String rroleCode;

    
   
    public String getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }
    public String getRuserId() {
        return this.ruserId;
    }
    
    public void setRuserId(String ruserId) {
        this.ruserId = ruserId;
    }
    public String getRroleName() {
        return this.rroleName;
    }
    
    public void setRroleName(String rroleName) {
        this.rroleName = rroleName;
    }
    public String getRdescription() {
        return this.rdescription;
    }
    
    public void setRdescription(String rdescription) {
        this.rdescription = rdescription;
    }
    public String getRroleCode() {
        return this.rroleCode;
    }
    
    public void setRroleCode(String rroleCode) {
        this.rroleCode = rroleCode;
    }




}


