package com.hedgehog.domain;
// Generated 2012-9-2 17:37:25 by Hibernate Tools 3.2.2.GA



/**
 * SysSysteminfo generated by hbm2java
 */
public class SysSysteminfo  implements java.io.Serializable {


     private String systemId;
     private String sname;
     private String sversion;
     private byte[] ssystemConfigData;
     private String slicensed;

    
   
    public String getSystemId() {
        return this.systemId;
    }
    
    public void setSystemId(String systemId) {
        this.systemId = systemId;
    }
    public String getSname() {
        return this.sname;
    }
    
    public void setSname(String sname) {
        this.sname = sname;
    }
    public String getSversion() {
        return this.sversion;
    }
    
    public void setSversion(String sversion) {
        this.sversion = sversion;
    }
    public byte[] getSsystemConfigData() {
        return this.ssystemConfigData;
    }
    
    public void setSsystemConfigData(byte[] ssystemConfigData) {
        this.ssystemConfigData = ssystemConfigData;
    }
    public String getSlicensed() {
        return this.slicensed;
    }
    
    public void setSlicensed(String slicensed) {
        this.slicensed = slicensed;
    }




}


