package com.hedgehog.domain;
// Generated 2012-9-2 17:37:25 by Hibernate Tools 3.2.2.GA


import java.sql.Timestamp;

/**
 * BizInfo generated by hbm2java
 */
public class BizInfo  implements java.io.Serializable {


     private String infoId;
     private String infoDomain;
     private String infoKey;
     private String infoValue;
     private String infoProperties;
     private Timestamp infoUpdatetime;

    
   
    public String getInfoId() {
        return this.infoId;
    }
    
    public void setInfoId(String infoId) {
        this.infoId = infoId;
    }
    public String getInfoDomain() {
        return this.infoDomain;
    }
    
    public void setInfoDomain(String infoDomain) {
        this.infoDomain = infoDomain;
    }
    public String getInfoKey() {
        return this.infoKey;
    }
    
    public void setInfoKey(String infoKey) {
        this.infoKey = infoKey;
    }
    public String getInfoValue() {
        return this.infoValue;
    }
    
    public void setInfoValue(String infoValue) {
        this.infoValue = infoValue;
    }
    public String getInfoProperties() {
        return this.infoProperties;
    }
    
    public void setInfoProperties(String infoProperties) {
        this.infoProperties = infoProperties;
    }
    public Timestamp getInfoUpdatetime() {
        return this.infoUpdatetime;
    }
    
    public void setInfoUpdatetime(Timestamp infoUpdatetime) {
        this.infoUpdatetime = infoUpdatetime;
    }




}


