package com.hedgehog.domain;
// Generated 2012-9-2 17:37:25 by Hibernate Tools 3.2.2.GA


import java.sql.Timestamp;

/**
 * SysEvent generated by hbm2java
 */
public class SysEvent  implements java.io.Serializable {


     private String eventId;
     private String euLoginName;
     private String euserId;
     private Timestamp edateTime;
     private String eapplicationId;
     private String eaAppName;
     private String emName;
     private String emPageCode;
     private String efrom;
     private byte etype;
     private String eip;
     private String erecord;

    
   
    public String getEventId() {
        return this.eventId;
    }
    
    public void setEventId(String eventId) {
        this.eventId = eventId;
    }
    public String getEuLoginName() {
        return this.euLoginName;
    }
    
    public void setEuLoginName(String euLoginName) {
        this.euLoginName = euLoginName;
    }
    public String getEuserId() {
        return this.euserId;
    }
    
    public void setEuserId(String euserId) {
        this.euserId = euserId;
    }
    public Timestamp getEdateTime() {
        return this.edateTime;
    }
    
    public void setEdateTime(Timestamp edateTime) {
        this.edateTime = edateTime;
    }
    public String getEapplicationId() {
        return this.eapplicationId;
    }
    
    public void setEapplicationId(String eapplicationId) {
        this.eapplicationId = eapplicationId;
    }
    public String getEaAppName() {
        return this.eaAppName;
    }
    
    public void setEaAppName(String eaAppName) {
        this.eaAppName = eaAppName;
    }
    public String getEmName() {
        return this.emName;
    }
    
    public void setEmName(String emName) {
        this.emName = emName;
    }
    public String getEmPageCode() {
        return this.emPageCode;
    }
    
    public void setEmPageCode(String emPageCode) {
        this.emPageCode = emPageCode;
    }
    public String getEfrom() {
        return this.efrom;
    }
    
    public void setEfrom(String efrom) {
        this.efrom = efrom;
    }
    public byte getEtype() {
        return this.etype;
    }
    
    public void setEtype(byte etype) {
        this.etype = etype;
    }
    public String getEip() {
        return this.eip;
    }
    
    public void setEip(String eip) {
        this.eip = eip;
    }
    public String getErecord() {
        return this.erecord;
    }
    
    public void setErecord(String erecord) {
        this.erecord = erecord;
    }




}


