package com.hedgehog.domain;
// Generated 2012-9-2 17:37:25 by Hibernate Tools 3.2.2.GA



/**
 * SysFieldvalue generated by hbm2java
 */
public class SysFieldvalue  implements java.io.Serializable {


     private String valueId;
     private String vfKey;
     private String vtext;
     private String vcode;
     private int vshowOrder;

    
   
    public String getValueId() {
        return this.valueId;
    }
    
    public void setValueId(String valueId) {
        this.valueId = valueId;
    }
    public String getVfKey() {
        return this.vfKey;
    }
    
    public void setVfKey(String vfKey) {
        this.vfKey = vfKey;
    }
    public String getVtext() {
        return this.vtext;
    }
    
    public void setVtext(String vtext) {
        this.vtext = vtext;
    }
    public String getVcode() {
        return this.vcode;
    }
    
    public void setVcode(String vcode) {
        this.vcode = vcode;
    }
    public int getVshowOrder() {
        return this.vshowOrder;
    }
    
    public void setVshowOrder(int vshowOrder) {
        this.vshowOrder = vshowOrder;
    }




}


