package com.hedgehog.outletss.domain;

import static org.apache.commons.lang.builder.EqualsBuilder.reflectionEquals;
import static org.apache.commons.lang.builder.HashCodeBuilder.reflectionHashCode;
import static org.apache.commons.lang.builder.ToStringBuilder.reflectionToString;

import javax.persistence.Column;
// Generated 2012-10-7 17:15:19 by Hibernate Tools 3.2.2.GA



/**
 * BizInfoPK generated by hbm2java
 */
public class BizInfoPK  implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;


     /**
      *                @hibernate.property
 *                 column="Info_subject"
 *                 length="50"
 *             
     */
     private String infoSubject;
     /**
      *                @hibernate.property
 *                 column="Info_key"
 *                 length="100"
 *             
     */
     private String infoKey;
     
     public BizInfoPK() {
     }

     public BizInfoPK(String infoSubject, String infoKey) {
        this.infoSubject = infoSubject;
        this.infoKey = infoKey;
     }

    
   
    /**       
     *      *                @hibernate.property
     *                 column="Info_subject"
     *                 length="50"
     *             
     */
     @Column(name="Info_subject",length=100,nullable=false)
    public String getInfoSubject() {
        return this.infoSubject;
    }
    
    public void setInfoSubject(String infoSubject) {
        this.infoSubject = infoSubject;
    }
    /**       
     *      *                @hibernate.property
     *                 column="Info_key"
     *                 length="100"
     *             
     */
    @Column(name="Info_key",length=100,nullable=false)
    public String getInfoKey() {
        return this.infoKey;
    }
    
    public void setInfoKey(String infoKey) {
        this.infoKey = infoKey;
    }
    
      // plumbing
 	  @Override
 	  public boolean equals(Object obj) {
 	    return reflectionEquals(this, obj);
 	  }
 	  
 	  @Override
 	  public int hashCode() {
 	    return reflectionHashCode(this);
 	  }
 	  
 	  @Override
 	  public String toString() {
 	    return reflectionToString(this);
 	  }
}


