package com.hedgehog.outletss.domain;
// Generated 2012-9-2 17:37:25 by Hibernate Tools 3.2.2.GA



/**
 * SysGroup generated by hbm2java
 */
public class SysGroup  implements java.io.Serializable {


     private String groupId;
     private String gcname;
     private String gparentId;
     private int gshowOrder;
     private Integer glevel;
     private Integer gchildCount;
     private Byte gdelete;

    
   
    public String getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }
    public String getGcname() {
        return this.gcname;
    }
    
    public void setGcname(String gcname) {
        this.gcname = gcname;
    }
    public String getGparentId() {
        return this.gparentId;
    }
    
    public void setGparentId(String gparentId) {
        this.gparentId = gparentId;
    }
    public int getGshowOrder() {
        return this.gshowOrder;
    }
    
    public void setGshowOrder(int gshowOrder) {
        this.gshowOrder = gshowOrder;
    }
    public Integer getGlevel() {
        return this.glevel;
    }
    
    public void setGlevel(Integer glevel) {
        this.glevel = glevel;
    }
    public Integer getGchildCount() {
        return this.gchildCount;
    }
    
    public void setGchildCount(Integer gchildCount) {
        this.gchildCount = gchildCount;
    }
    public Byte getGdelete() {
        return this.gdelete;
    }
    
    public void setGdelete(Byte gdelete) {
        this.gdelete = gdelete;
    }




}


