package com.hedgehog.outletss.domain;
// Generated 2012-9-2 17:37:25 by Hibernate Tools 3.2.2.GA



/**
 * SysModuleextpermission generated by hbm2java
 */
public class SysModuleextpermission  implements java.io.Serializable {


     private SysModuleextpermissionPK comp_id;
     private String extPermissionId;
     private String permissionName;

   
   
    public SysModuleextpermissionPK getComp_id() {
        return this.comp_id;
    }
    
    public void setComp_id(SysModuleextpermissionPK comp_id) {
        this.comp_id = comp_id;
    }
    public String getExtPermissionId() {
        return this.extPermissionId;
    }
    
    public void setExtPermissionId(String extPermissionId) {
        this.extPermissionId = extPermissionId;
    }
    public String getPermissionName() {
        return this.permissionName;
    }
    
    public void setPermissionName(String permissionName) {
        this.permissionName = permissionName;
    }




}


