package com.hedgehog.outletss.domain;
// Generated 2012-9-2 17:37:25 by Hibernate Tools 3.2.2.GA



/**
 * SysModuleextpermissionPK generated by hbm2java
 */
public class SysModuleextpermissionPK  implements java.io.Serializable {


     private String moduleId;
     private Integer permissionValue;

    public SysModuleextpermissionPK() {
    }

    public SysModuleextpermissionPK(String moduleId, Integer permissionValue) {
       this.moduleId = moduleId;
       this.permissionValue = permissionValue;
    }
   
    public String getModuleId() {
        return this.moduleId;
    }
    
    public void setModuleId(String moduleId) {
        this.moduleId = moduleId;
    }
    public Integer getPermissionValue() {
        return this.permissionValue;
    }
    
    public void setPermissionValue(Integer permissionValue) {
        this.permissionValue = permissionValue;
    }




}


