package com.hedgehog.outletss.domain;
// Generated 2012-9-16 16:58:05 by Hibernate Tools 3.2.2.GA



/**
 * SysRoleapplicationPK generated by hbm2java
 */
public class SysRoleapplicationPK  implements java.io.Serializable {


     /**
      *                @hibernate.property
 *                 column="A_RoleID"
 *                 length="40"
 *             
     */
     private Integer aroleId;
     /**
      *                @hibernate.property
 *                 column="A_ApplicationID"
 *                 length="40"
 *             
     */
     private Integer aapplicationId;

    public SysRoleapplicationPK() {
    }

    public SysRoleapplicationPK(Integer aroleId, Integer aapplicationId) {
       this.aroleId = aroleId;
       this.aapplicationId = aapplicationId;
    }
   
    /**       
     *      *                @hibernate.property
     *                 column="A_RoleID"
     *                 length="40"
     *             
     */
    public Integer getAroleId() {
        return this.aroleId;
    }
    
    public void setAroleId(Integer aroleId) {
        this.aroleId = aroleId;
    }
    /**       
     *      *                @hibernate.property
     *                 column="A_ApplicationID"
     *                 length="40"
     *             
     */
    public Integer getAapplicationId() {
        return this.aapplicationId;
    }
    
    public void setAapplicationId(Integer aapplicationId) {
        this.aapplicationId = aapplicationId;
    }




}


