package com.hedgehog.outletss.domain;
// Generated 2012-9-2 17:37:25 by Hibernate Tools 3.2.2.GA



/**
 * SysRolepermission generated by hbm2java
 */
public class SysRolepermission  implements java.io.Serializable {


     private SysRolepermissionPK comp_id;
     private String permissionId;
     private Integer pvalue;
   
   
    public SysRolepermissionPK getComp_id() {
        return this.comp_id;
    }
    
    public void setComp_id(SysRolepermissionPK comp_id) {
        this.comp_id = comp_id;
    }
    public String getPermissionId() {
        return this.permissionId;
    }
    
    public void setPermissionId(String permissionId) {
        this.permissionId = permissionId;
    }
    public Integer getPvalue() {
        return this.pvalue;
    }
    
    public void setPvalue(Integer pvalue) {
        this.pvalue = pvalue;
    }




}


