package com.hedgehog.domain;
// Generated 2012-9-2 17:37:25 by Hibernate Tools 3.2.2.GA



/**
 * SysApplication generated by hbm2java
 */
public class SysApplication  implements java.io.Serializable {


     private String applicationId;
     private String aappName;
     private String aappDescription;
     private String aappUrl;
     private Integer aorder;

    
   
    public String getApplicationId() {
        return this.applicationId;
    }
    
    public void setApplicationId(String applicationId) {
        this.applicationId = applicationId;
    }
    public String getAappName() {
        return this.aappName;
    }
    
    public void setAappName(String aappName) {
        this.aappName = aappName;
    }
    public String getAappDescription() {
        return this.aappDescription;
    }
    
    public void setAappDescription(String aappDescription) {
        this.aappDescription = aappDescription;
    }
    public String getAappUrl() {
        return this.aappUrl;
    }
    
    public void setAappUrl(String aappUrl) {
        this.aappUrl = aappUrl;
    }
    public Integer getAorder() {
        return this.aorder;
    }
    
    public void setAorder(Integer aorder) {
        this.aorder = aorder;
    }




}


