package com.hedgehog.domain;
// Generated 2012-9-2 17:37:25 by Hibernate Tools 3.2.2.GA



/**
 * SysModule generated by hbm2java
 */
public class SysModule  implements java.io.Serializable {


     private String moduleId;
     private String mapplicationId;
     private String mparentId;
     private String mpageCode;
     private String mcname;
     private String mdirectory;
     private String morderLevel;
     private Byte misSystem;
     private Byte mclose;
     private String micon;

    
   
    public String getModuleId() {
        return this.moduleId;
    }
    
    public void setModuleId(String moduleId) {
        this.moduleId = moduleId;
    }
    public String getMapplicationId() {
        return this.mapplicationId;
    }
    
    public void setMapplicationId(String mapplicationId) {
        this.mapplicationId = mapplicationId;
    }
    public String getMparentId() {
        return this.mparentId;
    }
    
    public void setMparentId(String mparentId) {
        this.mparentId = mparentId;
    }
    public String getMpageCode() {
        return this.mpageCode;
    }
    
    public void setMpageCode(String mpageCode) {
        this.mpageCode = mpageCode;
    }
    public String getMcname() {
        return this.mcname;
    }
    
    public void setMcname(String mcname) {
        this.mcname = mcname;
    }
    public String getMdirectory() {
        return this.mdirectory;
    }
    
    public void setMdirectory(String mdirectory) {
        this.mdirectory = mdirectory;
    }
    public String getMorderLevel() {
        return this.morderLevel;
    }
    
    public void setMorderLevel(String morderLevel) {
        this.morderLevel = morderLevel;
    }
    public Byte getMisSystem() {
        return this.misSystem;
    }
    
    public void setMisSystem(Byte misSystem) {
        this.misSystem = misSystem;
    }
    public Byte getMclose() {
        return this.mclose;
    }
    
    public void setMclose(Byte mclose) {
        this.mclose = mclose;
    }
    public String getMicon() {
        return this.micon;
    }
    
    public void setMicon(String micon) {
        this.micon = micon;
    }




}


