package com.hedgehog.domain;
// Generated 2012-9-2 17:37:25 by Hibernate Tools 3.2.2.GA


import java.sql.Timestamp;

/**
 * SysOnline generated by hbm2java
 */
public class SysOnline  implements java.io.Serializable {


     private String osessionId;
     private String onlineId;
     private String ouserName;
     private String oip;
     private Timestamp ologinTime;
     private Timestamp olastTime;
     private String olastUrl;

    
   
    public String getOsessionId() {
        return this.osessionId;
    }
    
    public void setOsessionId(String osessionId) {
        this.osessionId = osessionId;
    }
    public String getOnlineId() {
        return this.onlineId;
    }
    
    public void setOnlineId(String onlineId) {
        this.onlineId = onlineId;
    }
    public String getOuserName() {
        return this.ouserName;
    }
    
    public void setOuserName(String ouserName) {
        this.ouserName = ouserName;
    }
    public String getOip() {
        return this.oip;
    }
    
    public void setOip(String oip) {
        this.oip = oip;
    }
    public Timestamp getOloginTime() {
        return this.ologinTime;
    }
    
    public void setOloginTime(Timestamp ologinTime) {
        this.ologinTime = ologinTime;
    }
    public Timestamp getOlastTime() {
        return this.olastTime;
    }
    
    public void setOlastTime(Timestamp olastTime) {
        this.olastTime = olastTime;
    }
    public String getOlastUrl() {
        return this.olastUrl;
    }
    
    public void setOlastUrl(String olastUrl) {
        this.olastUrl = olastUrl;
    }




}


