package com.hedgehog.domain;
// Generated 2012-9-2 17:37:25 by Hibernate Tools 3.2.2.GA



/**
 * SysRolepermissionPK generated by hbm2java
 */
public class SysRolepermissionPK  implements java.io.Serializable {


     private String proleId;
     private String papplicationId;
     private String ppageCode;

    public SysRolepermissionPK() {
    }

    public SysRolepermissionPK(String proleId, String papplicationId, String ppageCode) {
       this.proleId = proleId;
       this.papplicationId = papplicationId;
       this.ppageCode = ppageCode;
    }
   
    public String getProleId() {
        return this.proleId;
    }
    
    public void setProleId(String proleId) {
        this.proleId = proleId;
    }
    public String getPapplicationId() {
        return this.papplicationId;
    }
    
    public void setPapplicationId(String papplicationId) {
        this.papplicationId = papplicationId;
    }
    public String getPpageCode() {
        return this.ppageCode;
    }
    
    public void setPpageCode(String ppageCode) {
        this.ppageCode = ppageCode;
    }




}


