package com.hedgehog.domain;
// Generated 2012-9-2 17:37:25 by Hibernate Tools 3.2.2.GA


import static org.apache.commons.lang.builder.EqualsBuilder.reflectionEquals;
import static org.apache.commons.lang.builder.HashCodeBuilder.reflectionHashCode;
import static org.apache.commons.lang.builder.ToStringBuilder.reflectionToString;

import java.sql.Timestamp;
import java.util.Collection;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

/**
 * SysUser generated by hbm2java
 */
@Entity
@Table(name="DIG_USER")
@org.hibernate.annotations.Proxy(lazy = false)
public class SysUser  implements java.io.Serializable,UserDetails {

	 private static final long serialVersionUID = 1L;
     private String userId;
     private String uloginName;
     private String upassword;
     private String ucname;
     private String uename;
     private String ugroupId;
     private String uemail;
     private byte utype;
     private byte ustatus;
     private String ulicence;
     private String umac;
     private String uremark;
     private String uidcard;
     private Byte usex;
     private Timestamp ubirthDay;
     private String umobileNo;
     private String uuserNo;
     private Timestamp uworkStartDate;
     private Timestamp uworkEndDate;
     private String ucompanyMail;
     private String utitle;
     private String uextension;
     private String uhomeTel;
     private String uphotoUrl;
     private Timestamp udateTime;
     private String ulastIp;
     private Timestamp ulastDateTime;
     private byte[] uextendField;

    
    @Id
 	@Column(name = "USERID",length = 32,unique=true, nullable=false)	
 	@GeneratedValue(generator = "system-uuid")
 	@GenericGenerator(name = "system-uuid", strategy = "uuid")
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    
	@Column(name="USER_NAME",length=50)
    public String getUloginName() {
        return this.uloginName;
    }
    
    public void setUloginName(String uloginName) {
        this.uloginName = uloginName;
    }
    public String getUpassword() {
        return this.upassword;
    }
    
    public void setUpassword(String upassword) {
        this.upassword = upassword;
    }
    public String getUcname() {
        return this.ucname;
    }
    
    public void setUcname(String ucname) {
        this.ucname = ucname;
    }
    public String getUename() {
        return this.uename;
    }
    
    public void setUename(String uename) {
        this.uename = uename;
    }
    public String getUgroupId() {
        return this.ugroupId;
    }
    
    public void setUgroupId(String ugroupId) {
        this.ugroupId = ugroupId;
    }
    public String getUemail() {
        return this.uemail;
    }
    
    public void setUemail(String uemail) {
        this.uemail = uemail;
    }
    public byte getUtype() {
        return this.utype;
    }
    
    public void setUtype(byte utype) {
        this.utype = utype;
    }
    public byte getUstatus() {
        return this.ustatus;
    }
    
    public void setUstatus(byte ustatus) {
        this.ustatus = ustatus;
    }
    public String getUlicence() {
        return this.ulicence;
    }
    
    public void setUlicence(String ulicence) {
        this.ulicence = ulicence;
    }
    public String getUmac() {
        return this.umac;
    }
    
    public void setUmac(String umac) {
        this.umac = umac;
    }
    public String getUremark() {
        return this.uremark;
    }
    
    public void setUremark(String uremark) {
        this.uremark = uremark;
    }
    public String getUidcard() {
        return this.uidcard;
    }
    
    public void setUidcard(String uidcard) {
        this.uidcard = uidcard;
    }
    public Byte getUsex() {
        return this.usex;
    }
    
    public void setUsex(Byte usex) {
        this.usex = usex;
    }
    public Timestamp getUbirthDay() {
        return this.ubirthDay;
    }
    
    public void setUbirthDay(Timestamp ubirthDay) {
        this.ubirthDay = ubirthDay;
    }
    public String getUmobileNo() {
        return this.umobileNo;
    }
    
    public void setUmobileNo(String umobileNo) {
        this.umobileNo = umobileNo;
    }
    public String getUuserNo() {
        return this.uuserNo;
    }
    
    public void setUuserNo(String uuserNo) {
        this.uuserNo = uuserNo;
    }
    public Timestamp getUworkStartDate() {
        return this.uworkStartDate;
    }
    
    public void setUworkStartDate(Timestamp uworkStartDate) {
        this.uworkStartDate = uworkStartDate;
    }
    public Timestamp getUworkEndDate() {
        return this.uworkEndDate;
    }
    
    public void setUworkEndDate(Timestamp uworkEndDate) {
        this.uworkEndDate = uworkEndDate;
    }
    public String getUcompanyMail() {
        return this.ucompanyMail;
    }
    
    public void setUcompanyMail(String ucompanyMail) {
        this.ucompanyMail = ucompanyMail;
    }
    public String getUtitle() {
        return this.utitle;
    }
    
    public void setUtitle(String utitle) {
        this.utitle = utitle;
    }
    public String getUextension() {
        return this.uextension;
    }
    
    public void setUextension(String uextension) {
        this.uextension = uextension;
    }
    public String getUhomeTel() {
        return this.uhomeTel;
    }
    
    public void setUhomeTel(String uhomeTel) {
        this.uhomeTel = uhomeTel;
    }
    public String getUphotoUrl() {
        return this.uphotoUrl;
    }
    
    public void setUphotoUrl(String uphotoUrl) {
        this.uphotoUrl = uphotoUrl;
    }
    public Timestamp getUdateTime() {
        return this.udateTime;
    }
    
    public void setUdateTime(Timestamp udateTime) {
        this.udateTime = udateTime;
    }
    public String getUlastIp() {
        return this.ulastIp;
    }
    
    public void setUlastIp(String ulastIp) {
        this.ulastIp = ulastIp;
    }
    public Timestamp getUlastDateTime() {
        return this.ulastDateTime;
    }
    
    public void setUlastDateTime(Timestamp ulastDateTime) {
        this.ulastDateTime = ulastDateTime;
    }
    public byte[] getUextendField() {
        return this.uextendField;
    }
    
    public void setUextendField(byte[] uextendField) {
        this.uextendField = uextendField;
    }

/**
 * 实现UserDetails接口方法
 */
	@Override
	public Collection<? extends GrantedAuthority> getAuthorities() {
		// TODO Auto-generated method stub
		return null;
	}


	@Override
	public String getPassword() {
		// TODO Auto-generated method stub
		return this.upassword;
	}


	@Override
	public String getUsername() {
		// TODO Auto-generated method stub
		return this.uloginName;
	}


	@Override
	public boolean isAccountNonExpired() {
		// TODO Auto-generated method stub
		return true;
	}


	@Override
	public boolean isAccountNonLocked() {
		// TODO Auto-generated method stub
		return true;
	}


	@Override
	public boolean isCredentialsNonExpired() {
		// TODO Auto-generated method stub
		return true;
	}


	@Override
	public boolean isEnabled() {
		// TODO Auto-generated method stub
		return this.ustatus==0?true:false;		
	}
	// plumbing
    @Override
    public boolean equals(Object obj) {
      return reflectionEquals(this, obj);
    }
    
    @Override
    public int hashCode() {
      return reflectionHashCode(this);
    }
    
    @Override
    public String toString() {
      return reflectionToString(this);
    }

}


