package com.hedgehog.outletss.domain;
// Generated 2012-9-2 17:37:25 by Hibernate Tools 3.2.2.GA


import java.sql.Timestamp;

/**
 * BizNew generated by hbm2java
 */
public class BizNew  implements java.io.Serializable {


     private String newsId;
     private String newsTitle;
     private String newsCate;
     private String newsContent;
     private String newsKeywords;
     private String newsSummery;
     private String newsProperties;
     private Timestamp newsUpdatetime;

   
   
    public String getNewsId() {
        return this.newsId;
    }
    
    public void setNewsId(String newsId) {
        this.newsId = newsId;
    }
    public String getNewsTitle() {
        return this.newsTitle;
    }
    
    public void setNewsTitle(String newsTitle) {
        this.newsTitle = newsTitle;
    }
    public String getNewsCate() {
        return this.newsCate;
    }
    
    public void setNewsCate(String newsCate) {
        this.newsCate = newsCate;
    }
    public String getNewsContent() {
        return this.newsContent;
    }
    
    public void setNewsContent(String newsContent) {
        this.newsContent = newsContent;
    }
    public String getNewsKeywords() {
        return this.newsKeywords;
    }
    
    public void setNewsKeywords(String newsKeywords) {
        this.newsKeywords = newsKeywords;
    }
    public String getNewsSummery() {
        return this.newsSummery;
    }
    
    public void setNewsSummery(String newsSummery) {
        this.newsSummery = newsSummery;
    }
    public String getNewsProperties() {
        return this.newsProperties;
    }
    
    public void setNewsProperties(String newsProperties) {
        this.newsProperties = newsProperties;
    }
    public Timestamp getNewsUpdatetime() {
        return this.newsUpdatetime;
    }
    
    public void setNewsUpdatetime(Timestamp newsUpdatetime) {
        this.newsUpdatetime = newsUpdatetime;
    }




}


