package com.hedgehog.outletss.domain;
// Generated 2012-9-16 16:58:05 by Hibernate Tools 3.2.2.GA



/**
 * SysRolepermissionPK generated by hbm2java
 */
public class SysRolepermissionPK  implements java.io.Serializable {


     /**
      *                @hibernate.property
 *                 column="P_RoleID"
 *                 length="40"
 *             
     */
     private String proleId;
     /**
      *                @hibernate.property
 *                 column="P_ApplicationID"
 *                 length="40"
 *             
     */
     private String papplicationId;
     /**
      *                @hibernate.property
 *                 column="P_PageCode"
 *                 length="20"
 *             
     */
     private String ppageCode;

    public SysRolepermissionPK() {
    }

    public SysRolepermissionPK(String proleId, String papplicationId, String ppageCode) {
       this.proleId = proleId;
       this.papplicationId = papplicationId;
       this.ppageCode = ppageCode;
    }
   
    /**       
     *      *                @hibernate.property
     *                 column="P_RoleID"
     *                 length="40"
     *             
     */
    public String getProleId() {
        return this.proleId;
    }
    
    public void setProleId(String proleId) {
        this.proleId = proleId;
    }
    /**       
     *      *                @hibernate.property
     *                 column="P_ApplicationID"
     *                 length="40"
     *             
     */
    public String getPapplicationId() {
        return this.papplicationId;
    }
    
    public void setPapplicationId(String papplicationId) {
        this.papplicationId = papplicationId;
    }
    /**       
     *      *                @hibernate.property
     *                 column="P_PageCode"
     *                 length="20"
     *             
     */
    public String getPpageCode() {
        return this.ppageCode;
    }
    
    public void setPpageCode(String ppageCode) {
        this.ppageCode = ppageCode;
    }




}


